Description: CI definition for device-identification-data
Parameters:
  GitHubOrganisationName:
    Type: String
    Description: Name of organisation to which the repository belongs (e.g. bbc)
    Default: bbc
  GitHubRepositoryName:
    Type: String
    Description: Name of GitHub Repository
    Default: device-identification-data
  GitHubRepositoryBranchName:
    Type: String
    Description: Name of Git branch to build from
    Default: master
  TestBucketName:
    Type: String
    Description: Name of the test bucket where data is deployed too
    Default: test-device-identification-data-bucket-1u0gmv027tr5a
  LiveBucketName:
    Type: String
    Description: Name of the live bucket where data is deployed too
    Default: live-device-identification-data-bucket-8wua42dtu3nc
  DevelopmentAccount:
    Type: String
    Default: 119990297419
  ProductionAccount:
    Type: String
    Default: 198243407611
Resources:
  TestCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::979446310614:policy/CodeBuildBasePolicy
      Policies:
        - PolicyName: device-identification-data-codebuild-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub "arn:aws:s3:::${TestBucketName}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${TestBucketName}"
  TestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: test-device-identification-data
      Description: CodeBuild project for device-identification-data
      ServiceRole: !GetAtt TestCodeBuildRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: SERVICE_ROLE
        Image: 979446310614.dkr.ecr.eu-west-1.amazonaws.com/itv-ci-images-node:latest
        EnvironmentVariables:
          - Name: BUCKET_NAME
            Value: !Ref TestBucketName
            Type: PLAINTEXT
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5
      EncryptionKey: "alias/codepipeline-kms-key"
      Artifacts:
        Type: CODEPIPELINE
  LiveCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::979446310614:policy/CodeBuildBasePolicy
      Policies:
        - PolicyName: device-identification-data-codebuild-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub "arn:aws:s3:::${LiveBucketName}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${LiveBucketName}"
  LiveCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: live-device-identification-data
      Description: CodeBuild project for device-identification-data
      ServiceRole: !GetAtt LiveCodeBuildRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: SERVICE_ROLE
        Image: 979446310614.dkr.ecr.eu-west-1.amazonaws.com/itv-ci-images-node:latest
        EnvironmentVariables:
          - Name: BUCKET_NAME
            Value: !Ref LiveBucketName
            Type: PLAINTEXT
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5
      EncryptionKey: "alias/codepipeline-kms-key"
      Artifacts:
        Type: CODEPIPELINE
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: device-identification-data
      RestartExecutionOnUpdate: true
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/codepipeline-execution-role"
      ArtifactStore:
        Type: S3
        Location: itv-ci-jobs-artifactsbucket-oqsnfnwyfn4z
        EncryptionKey:
          Id: "arn:aws:kms:eu-west-1:979446310614:alias/codepipeline-kms-key"
          Type: "KMS"
      Stages:
        - Name: Source
          Actions:
            - Name: Clone-From-GitHub
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              OutputArtifacts:
                - Name: GitHubSource
              Configuration:
                Owner: !Ref GitHubOrganisationName
                Repo: !Ref GitHubRepositoryName
                Branch: !Ref GitHubRepositoryBranchName
                OAuthToken: "{{resolve:secretsmanager:/CodeBuild/Github:SecretString:GithubAccessToken}}"
                PollForSourceChanges: false

        - Name: Deploy-To-Test
          Actions:
            - Name: Deploy-Stack
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: test-device-identification-data
                RoleArn: !Sub "arn:aws:iam::${DevelopmentAccount}:role/codepipeline-cloudformation-role"
                TemplatePath: GitHubSource::stacks/bucket.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/bucket/test.json
              RoleArn: !Sub "arn:aws:iam::${DevelopmentAccount}:role/codepipeline-execution-role"
            - Name: Deploy-Data
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              Configuration:
                ProjectName: !Ref TestCodeBuildProject

        - Name: Deploy-To-Live
          Actions:
            - Name: Deploy-Stack
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: live-device-identification-data
                RoleArn: !Sub "arn:aws:iam::${ProductionAccount}:role/codepipeline-cloudformation-role"
                TemplatePath: GitHubSource::stacks/bucket.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/bucket/live.json
              RoleArn: !Sub "arn:aws:iam::${ProductionAccount}:role/codepipeline-execution-role"
            - Name: Deploy-Data
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              Configuration:
                ProjectName: !Ref LiveCodeBuildProject

  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:secretsmanager:/CodeBuild/Github:SecretString:GithubWebhookSecret}}"
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/master
      TargetPipeline: !Ref CodePipeline
      TargetAction: Clone-From-GitHub
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true
